[workspace]
members = [
    "chain-reader/chain-reader",
    "mock",
    "core/chain/substrate",
    "indexer/main",
    "plugin/plugin",
    "plugin/test-block",
    "plugin/test-extrinsic",
    "plugin/test-event",
    "plugin/test-solana-block",
    "plugin/test-solana-transaction",
    "core/chain/solana",
]
exclude = ["code-compiler/generated"]
