[workspace]
members = [
    "chain-reader",
    "indexer/main",
    "plugin-examples/block",
    "mock",
    "core/chain/substrate",
]
exclude = [
    "code-compiler" # Ignore this python project because it contains Cargo.toml which is only used for populating new index
]
