[workspace]
members = [
    "chain-reader/chain-reader",
    "mock",
    "core/chain/substrate",
    "indexer/main",
    "plugin/plugin",
    "plugin/test-plugin", # Should be rename to test-substrate-block
    "plugin/test-extrinsic",
    "plugin/test-event",
    "core/chain/solana",
]
exclude = ["code-compiler/generated"]
