[package]
name = "massbit-chain-ethereum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
serde = "1.0.126"
log = "0.4.14"
env_logger = "0.9.0"
bs58 = "0.4.0"

############# Ethereum
[dependencies.web3]
package = "web3"
#git = "https://github.com/tomusdrw/rust-web3.git"
git = "https://github.com/graphprotocol/rust-web3"
branch = "master"

############# End Ethereum