[package]
name = "block"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
plugin = { path = "../../../plugin/plugin" } # Todo copy these to our compiler repo
massbit-chain-substrate = { path = "../../../core/chain/substrate"} # Todo copy these to our compiler repo
index-store = { path = "../../../core/index-store"} # Todo copy these to our compiler repo
structmap = "0.1.5"
structmap-derive = "0.1.5"
chrono = "0.4.19"

[lib]
crate-type = ["cdylib"]